# .streamlit/secrets.toml.example
# DO NOT COMMIT REAL SECRETS. This file is for structure only.
# The real values must be manually pasted into the Streamlit Cloud Secrets UI.

[general]
environment = "prod"
# Example of a generic secret
admin_email = "admin@example.com"

[google_service_account]
# GSpread/Firestore Service Account JSON structure
type = "service_account"
project_id = "your-gcp-project-id"
private_key_id = "abc1234..."
private_key = """-----BEGIN PRIVATE KEY-----\n...\n-----END PRIVATE KEY-----\n"""
client_email = "service-account@project.iam.gserviceaccount.com"
client_id = "1234567890"

[supabase]
url = "https://your-supabase-project.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..." # Anon or Service Role key
database_name = "postgres"
schema = "public"

[auth]
# For streamlit-authenticator
cookie_name = "myapp_auth"
signature_key = "very_secret_signing_key_for_cookies"
# Credentials for demo only (MUST BE HASHED IN PRODUCTION)
names = "Admin User,Guest User"
usernames = "admin,guest"
passwords = "password123,guestpass"
